### PR TITLE
added 4 more FBO sources

### PR DESCRIPTION
**Pull request by u3dreal**
ScanlineSource ( was there already ) added CircleSource, QuadSource, BrickSource and SyphonSource (not visible).

Bildschirmfoto 2022-07-27 um 02 05 39

The SyphonFBO is disabled since it would not run on rpi.

[OSX only]
For Syphon to work you need to install ofxSyphon addon and add "ofxSyphon"
to the addons.make of ofxPiMapper. Then uncomment all the syphon lines in the code. So far the SyphonClient will choose the first Syphon source presented to him. ( You might want to start the server later ).

### CODE REVIEW

**Comment by kr15h** [comment]
Architecture-wise I would rather add them as sources, but OK.

**Comment by u3dreal** [comment]
Hello Yes you might be right about that ... 
i guess you mean adding syphon as an extra source  .... i will have a look  ... is there a place to meet other devs ??
grettings

**Comment by kr15h** [comment]
On the other hand I think it is good that you added the sources in fbo example, not in the main code. There is no place where to meet other devs, but some kind of community platform is on my mind. Do you mean physical space or more like a forum or chat?

**Comment by u3dreal** [comment]
And i guess it was way easier to implement as a fbo :) just about 6 lines :)
And yes i have been around here for some time ... i figured it's a good project to get into c++.
I also think i would be nice to get things organized a bit .. 

To have one main repo everybody contributes to.

The Project has way to much potential :) 
And yes i would be nice to have a community :)

**Comment by kr15h** [comment]
True, FBO sources are very flexible. That is nice to know that you chose the project to get into C++. That is very encouraging. I wonder what would be your view on what could be organized better?
I will see what I can do with the community aspect. I think Arduino is a good example. There are tons of boards similar to Arduino out there, but many people still chose Arduino as an entry point and that I think is mainly because it has a very active community.

**Comment by u3dreal** [comment]
i sent you an e.mail to your guthub mail. cya

**Pull request merged**
